version: '3.3'
services:
  web:
    image: tubes-1:latest
    ports:
      - 8008:80
    hostname: web-tubes-1
    env_file: ./src/.env
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    hostname: db-tubes-1
    env_file: ./src/.env
    volumes:
      - ./mysql:/var/lib/mysql
    command:
        - '--skip-log-bin'
networks:
  web-mysql:
    driver: bridge
